<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-02-02 at 13:37:03.
 */
class PlaceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Place
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {   require_once '../Place.php';
        $this->object = new Place(1, "name","musuem", 3, 23, 25, "", "1", "img");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Place::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // require_once '../Place.php';
//         $this->object ->place_id = "22";
//     $this->object ->place_name = "name";
//   $this->object ->place_type = "musuem";
//      $this->object ->rating = "5";
//   $this->object ->latitude = "23";
//    $this->object ->longitude = "52";
//    $this->object ->icon = "as";
//      $this->object ->open = "asas";
//        //$this->price_level = $price_level;
    //   $this->cover_image = "as";
//     $expected= "name";
//     $actual =  "name";
//   //    $this->object = new Place(1, "name","musuem", 3, 23, 25, "", "1", "img");
//   //    $this->assertEqual($actual,"name");
//      $this->object->assertEquals( 
//            $expected, 
//            $actual, 
//            "actual value is not equals to expected"
//        ); 
  
     //   $place->checkOpen();
    $this->assertSame($this->object->getName(),"name");
    }

    /**
     * @covers Place::printPlace
     * @todo   Implement testPrintPlace().
     */
    public function testPrintPlace()
    {
        $expected = "<br>name\t3\t <a>img</a>";
           // $this->expectOutputString($expected);
            $this->object->printPlace();
    }

    /**
     * @covers Place::setCoverImage
     * @todo   Implement testSetCoverImage().
     */
    public function testSetCoverImage()
    {
         $this->cover_image="sd";
    }
}
